[project]
name = "mlops"
root = "."
languages = ["python"]

[resolve.python]
package_names = ["domain", "infrastructure", "usecase"]

[[layers]]
name = "src_domain"
paths = ["src/domain/**"]
allow = []
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["dataclasses", "pathlib", "typing"]

[[layers]]
name = "src_infrastructure"
paths = ["src/infrastructure/**"]
allow = ["src_domain"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["datetime", "kaggle", "lightgbm", "logging", "math", "matplotlib", "numpy", "omegaconf", "pandas", "pathlib", "polars", "seaborn", "sklearn", "subprocess", "typing", "yaml", "zipfile"]

[[layers]]
name = "src_usecase"
paths = ["src/usecase/**"]
allow = ["src_domain"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["datetime", "omegaconf", "pathlib", "typing", "yaml"]

[[layers]]
name = "tests_domain"
paths = ["tests/domain/**"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["pathlib", "pytest", "src", "typing"]

[[layers]]
name = "tests_infrastructure"
paths = ["tests/infrastructure/**"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["math", "numpy", "omegaconf", "pandas", "pathlib", "polars", "pytest", "src", "typing", "unittest", "yaml", "zipfile"]

[[layers]]
name = "tests_usecase"
paths = ["tests/usecase/**"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["omegaconf", "pathlib", "polars", "pytest", "src", "typing", "unittest", "yaml"]
