[project]
name = "mlops"
root = "."
languages = ["python"]

[resolve.python]
package_names = ["src"]

[[layers]]
name = "src_domain"
paths = ["src/domain/**"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["dataclasses", "pathlib", "typing"]
name_deny = ["gcp", "vertex", "lgbm", "titanic", "kaggle"]

[[layers]]
name = "src_infrastructure"
paths = ["src/infrastructure/**"]
allow = ["src_domain", "src_usecase"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["datetime", "google", "json", "kaggle", "lightgbm", "logging", "math", "matplotlib", "numpy", "omegaconf", "os", "pandas", "pathlib", "polars", "seaborn", "sklearn", "subprocess", "typing", "yaml", "zipfile"]
name_deny = ["titanic"]

[[layers]]
name = "src_usecase"
paths = ["src/usecase/**"]
allow = ["src_domain"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["collections", "dataclasses", "datetime", "fnmatch", "jinja2", "json", "logging", "numpy", "omegaconf", "pathlib", "polars", "scipy", "shutil", "typing", "yaml"]
name_deny = ["gcp", "vertex", "lgbm", "titanic", "kaggle"]

[[layers]]
name = "tests_domain"
paths = ["tests/domain/**"]
allow = ["src_domain"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["pathlib", "pytest", "src", "typing"]

[[layers]]
name = "tests_infrastructure"
paths = ["tests/infrastructure/**"]
allow = ["src_domain", "src_infrastructure"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["google", "json", "lightgbm", "math", "numpy", "omegaconf", "pandas", "pathlib", "polars", "pytest", "src", "typing", "unittest", "yaml", "zipfile"]

[[layers]]
name = "tests_usecase"
paths = ["tests/usecase/**"]
allow = ["src_domain", "src_usecase", "src_infrastructure"]
dependency_mode = "opt-in"
external_mode = "opt-in"
external_allow = ["google", "json", "numpy", "omegaconf", "pathlib", "polars", "pytest", "re", "src", "typing", "unittest", "yaml"]
